### ISSUE TITLE
Can I translate this note into English?

### ISSUE THREAD

**Issue by wuyichao71** [MasatakaYm/Molecular-Simulation#14]
I am a Ph.D. student in computational biophysics in Nanjing University. I use CafeMol for my research. The note is helpful for me, can I translate it into English?

**Comment by MasatakaYm** [comment]
Thank you for this suggestion.
Yes, you can translate my note into English. It should be helpful for many.

I would like to keep the original Japanese sources because I have been updating this document to note what I have learned.
Please remain the original Japanese sources (In other words, please put sources of your English version in a different directory) when you make PR.
